#!/bin/bash

#####INCREMNTAL IMPORT SCRIPT#####

##with echo to test
##./<executable filename> <property file path> <Hive Database Name> <USER_access to table> <DateValue> <DebugMode>



if [ "$#" -ne 5 ]; then
echo "Incorrect argument provided. Provide argument in position to->>  ./<executable filename> <property file path> <Hive Database Name> <USER_access to table> <DateValue for Incremental> <DebugMode>"
exit 0
fi


PROPERTY_FILE=./$1
HIVEDBNAME=$2
USER=$3
DATEVALUE=$4
DEBUG_MODE=$5

if [ -f "$PROPERTY_FILE" ]
then

echo "$PROPERTY_FILE found"
while IFS='=' read -r key value
do
key=$(echo $key)
eval ${key}=\${value}
done<"$PROPERTY_FILE"

USERNAME=${USERNAME}
PASSWORD=`cat ${PASSWORDFILEPATH}`
TABLENAME_FILE=${TABLENAMEFILE}
SERVICE_NAME=${SERVICENAME}
PORT=${PORT}
HOST=${HOST}
OPTIONAL_CONNECTION_DETAILS=${OPTIONAL_CONNECTION_DETAILS}

else
echo "$PROPERTY_FILE not found"
fi

if [ -z "$OPTIONAL_CONNECTION_DETAILS" ];
then
CONNECTION_STRING="jdbc:oracle:thin:$USERNAME/$PASSWORD@(DESCRIPTION = (ADDRESS = (PROTOCOL=tcp)(HOST=$HOST)(PORT=$PORT)) (CONNECT_DATA = (SERVICE_NAME=$SERVICE_NAME.agriculture.gov.ie))(HS=OK))"
else
CONNECTION_STRING="jdbc:oracle:thin:$USERNAME/$PASSWORD@(DESCRIPTION = (ADDRESS = (PROTOCOL=tcp)(HOST=$HOST)(PORT=$PORT)) (CONNECT_DATA = (SERVICE_NAME=$SERVICE_NAME.agriculture.gov.ie)$OPTIONAL_CONNECTION_DETAILS)(HS=OK))"
fi

#echo "$CONNECTION_STRING"

while read line;
do
TABLENAME=`echo $line | cut -d ',' -f1`
PKNAME=`echo $line | cut -d ',' -f2`
COLUMNNAME=`echo $line | cut -d ',' -f3`

SQOOP_COMMAND="sqoop import --connect \"$CONNECTION_STRING\" --table $USER.$TABLENAME --incremental lastmodified --merge-key $PKNAME --check-column $COLUMNNAME --last-value $DATEVALUE --target-dir '/tmp/$HIVEDBNAME/$TABLENAME' -m5 --verbose"


if [ "$DEBUG_MODE" == true ]
then
echo "$SQOOP_COMMAND"
else
bash -c "$SQOOP_COMMAND"
fi

done < $TABLENAME_FILE